DROP TABLE IF EXISTS USER;

CREATE TABLE IF NOT EXISTS USER(
    id      BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_date DATETIME NOT NULL,
    last_modified_date DATETIME NOT NULL
);

